let baseUrl = "https://apifoxmock.com/m1/4728220-0-default/api"

export default function http (url: string, data = {}, method = 'GET'){
	return new Promise((resolve, reject) => {
		uni.request({
			url: baseUrl + url,
			data,
			method: method,
			header: {
				'token': uni.getStorageSync('token') || ''
			},
			success: res => {
				console.log(res, 'res')
				// 判断状态码
				if (res.statusCode == 200){
					const resData = res.data as UTSJSONObject
					if (resData.code == 1){
						resolve(resData.data)
					}
					else if (resData.code == 0){
						uni.showToast({
							title: resData.msg,
							icon: 'none'
						})
						reject(resData.msg)
					}
				}
			},
			fail: () => {
				uni.showToast({
					title: '服务器请求异常',
					icon: 'none'
				})
			}
		})
	})
}